@startuml

title "No opponent exemple"

participant "Client 1" as c1
participant "Server" as s
participant "Client 2" as c2

== Join the server ==

note over c1, c2
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established


== Create game ==

c1->s: CREATE <size>
s->c1: WAITING_OPPONENT <text>


== No opponent yet ==
c1->s: PLACE <row> <column>
s->c1: ERROR -4



@enduml
