@startuml

title "A Player try to join a game that is already full"

participant "Client 1" as c1
participant "Server" as s
participant "Client 2" as c2
participant "Client 3" as c3

== Join the server ==

note over c1, c2
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: JOIN Player1
s->c1: OK

c2->s : Establish connection
c2<-->s : Connection established

c2->s: JOIN Player2
s->c2: OK

== A Player try to join a game that is already full ==

c3->s: JOIN Player3
s->c3: ERROR 1

@enduml
